#!/bin/bash
rm Strip.o Strip.elf Strip.hex

avr-gcc -Os -DF_CPU=8000000UL -mmcu=atmega8 -c Strip.c
avr-gcc -mmcu=atmega8 -o Strip.elf Strip.o
avr-objcopy -O ihex -R .eeprom Strip.elf Strip.hex
avr-objcopy -I ihex Strip.hex -O binary Strip.bin
#sudo avrdude -p t85 -c usbasp -P usb -U lfuse:w:0xe2:m -U hfuse:w:0xdd:m -U efuse:w:0xff:m -U flash:w:Strip.hex